---
director_uuid: <%= `bosh status --uuid ` %>
name: cf-mongooseim

releases:
- name: cf-mongooseim
  version: latest

compilation:
  workers: 2
  network: services1
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: m3.medium

update:
  canaries: 1
  canary_watch_time: 30000-180000
  update_watch_time: 30000-180000
  max_in_flight: 4

networks:
- name: services1
  type: manual
  subnets:
  - range: 10.0.0.0/24
    gateway: 10.0.0.1
    # Amazon reserves the first four IPs and the last IP for networking purposes
    reserved:
    - 10.0.0.2 - 10.0.0.4
    - 10.0.0.11
    - 10.0.0.5
    - 10.0.0.254
    static:
    - 10.0.0.6 - 10.0.0.10
    - 10.0.0.12
    dns:
    - 10.0.0.6
    cloud_properties:
      subnet: subnet-be56f5e7
- name: vip_network
  type: vip
  # Fake network properties to satisfy bosh diff
  subnets:
  - range: 127.0.99.0/24
    gateway: 127.0.99.1
    dns:
    - 127.0.99.250
  cloud_properties:
    security_groups:
    - bosh

resource_pools:
- name: services-small
  network: services1
  stemcell:
    name: bosh-aws-xen-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    instance_type: m3.medium

jobs:
  - name: mongooseim-server
    template: mongooseim-server
    instances: 1
    resource_pool: services-small
    persistent_disk: 4096
    networks:
    - name: services1
      static_ips:
      - 10.0.0.12
